steps:
  - name: gradle:8.7-jdk21-alpine
    id: build
    entrypoint: gradle
    args: ['-p', 'data-proxy', 'shadowJar']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:473.0.0-alpine
    args:
      - gcloud
      - functions
      - deploy
      - predictions-data-proxy
      - --gen2
      - --ingress-settings=all
      - --entry-point=com.github.ajablonski.Entrypoint
      - --source=data-proxy/build/libs
      - --region=us-central1
      - --trigger-http
      - --runtime=java21
      - --max-instances=2
      - --set-secrets=/etc/secrets/gtfs_secrets.json=gtfs-secrets-cta:1
    waitFor:
      - build
